version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: candidato_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: app_candidato
    ports:
      - '5435:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
